# Generated by Django 5.2.14 on 2026-05-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_user_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccess',
            name='user',
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_access', to='core.group'),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='user_access', to='core.permission'),
        ),
    ]
